<!-- Header -->
<a name="about"></a>
<div class="intro-header">
	<div class="container">

		<div class="row">
			<div class="col-lg-12">
				<div class="intro-message">
					<h1>Toko Keramik Geraldine</h1>
					<h3>Inventory Data Keramik</h3>
					
				</div>
			</div>
		</div>

	</div>
	<!-- /.container -->

</div>
<!-- /.intro-header -->
<div class="content-section-a">
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
		<div class="jumbotron">
        <h1>Selamat Datang</h1>

        <p class="lead">Kami Melayani Anda dengan Sepenuh Hati</p>

        <!-- <p><a class="btn btn-lg btn-success" href="index.php?r=data-stok">Get started with Yii</a></p> -->
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Resources</h2>

                <p>Sumber daya manusia adalah faktor penting yang selalu kami utamakan.  Perseroan secara konsisten mengembangkan keterampilan dan pengetahuan pegawainya dengan konsep inovatif dalam bekerja.    </p>

                <!-- <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p> -->
            </div>
            <div class="col-lg-4">
                <h2>History</h2>

                <p>Dengan mengandalkan teknologi terkini, Toko Keramik GG mampu memproduksi ubin sesuai dengan gaya hidup modern bagi seluruh pelanggan di dunia.  </p>

                <!-- <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p> -->
            </div>
            <div class="col-lg-4">
                <h2>Info</h2>

                <p>Keramik adalah salah satu pilihan lantai paling populer digunakan untuk rumah dan kantor di seluruh dunia. Ubin keramik juga banyak digunakan pada dinding. </p>

                <!-- <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p> -->
            </div>
        </div>
		</div>
	</div>
</div>
</div>
<!-- Page Content -->


<a  name="welcome"></a>
<div class="content-section-a">

	<div class="container">
		<div class="row">
			<div class="col-lg-5 col-sm-6">
				<hr class="section-heading-spacer">
				<div class="clearfix"></div>
				<h2 class="section-heading"><?php echo lang('selamat_datang_di_toko_keramik_geraldine'); ?></h2>
				<p class="lead"><?php echo lang('generated by Geraldine Agusta'); ?></p>
			</div>
			
		</div>

	</div>
	<!-- /.container -->

</div>
</div>
</div>
</div>

